#+title: PLN CDR draft: Issue 5
#+author: Gleefre
#+email: varedif.a.s@gmail.com

#+options: toc:nil
#+latex_header: \usepackage[margin=1in]{geometry}

* Issue 5 (Local nickname shadowing package's own name)
  :PROPERTIES:
  :CUSTOM_ID: issue-5
  :END:
** Description
   It is not clear whether it is valid to have a /local nickname/ in a package
   shadowing its own name or nickname.
** Examples
   #+BEGIN_SRC common-lisp
     (defpackage #:foo
       (:use)
       (:nicknames #:bar)
       (:local-nicknames (#:foo #:cl)
                         (#:bar #:cl)))
     ; => continuable error  (sbcl, ccl, abcl)
     ; => error  (lispworks)
     ; => ok  (ecl, acl, clasp)
   #+END_SRC
** Current behavior
   sbcl, ccl, abcl and lispwork signal an error.
** Proposal ALLOW
   It should be allowed to use package's own name or global nickname, but a
   style-warning can be signalled.
*** Rationale
   Such local nicknames are not likely to break anything. Even though they can be a
   bit confusing, this fact alone doesn't warrant an error being signalled.

   Moreover, on all implementations it is possible to obtain such nicknames, even if
   on some of them invoking the ~continue~ restart is going to be needed. This also
   suggests that cost of adoption is very low.
