#+title: PLN CDR draft: Issue 6
#+author: Gleefre
#+email: varedif.a.s@gmail.com

#+options: toc:nil
#+latex_header: \usepackage[margin=1in]{geometry}

* Issue 6 (Additional keyword argument to MAKE-PACKAGE)
  :PROPERTIES:
  :CUSTOM_ID: issue-6
  :END:
** Descriptions
   An additional keyword argument to ~make-package~ similar to the ~:use~ keyword
   argument would be a nice feature. There are only two implementations introducing
   this extension, unfortunately they use different API for this argument.

   Possible questions:
   - Does it accept an alist or a nested list?
   - Is the default value implementation-dependent, or is it an empty list?
** Current behavior
   sbcl, ccl, abcl, clasp, lispworks: no additional keyword argument.

   ecl: has an additional keyword argument ~:local-nicknames~, but it is undocumented
   and it segfaults on incorrect usage. The expected value is a list of conses:
   ~((nickname . package)*)~.

   acl: has an additional keyword argument ~:local-nicknames~. The expected value is
   a list of lists: ~((nickname package)*)~.
** Proposal EXTRA-KEYWORD-ARGUMENT-LIST
   Add ~:local-nicknames~ keyword argument to ~make-package~:
     : local-nicknames ::= ((nickname package)*)

   ~nickname~ --- a /string designator/.

   ~package~ --- a /package designator/.

   ~local-nicknames~ defaults to an /empty list/.
** Links
   See [[#make-package][make-package]].
