#+title: PLN CDR draft: Issue 9
#+author: Gleefre
#+email: varedif.a.s@gmail.com

#+options: toc:nil
#+latex_header: \usepackage[margin=1in]{geometry}

* Issue 9 (Empty package local name)
  :PROPERTIES:
  :CUSTOM_ID: issue-9
  :END:
** Description
   It is not clear whether it should be allowed to use ~""~ as a local nickname,
   and in the case this is allowed, whether it should affect the ~:xxxx~ syntax.
** Examples
   #+BEGIN_SRC common-lisp
     (defpackage #:foo
       (:use #:cl)
       (:local-nicknames ("" #:cl)))

     (in-package #:foo)

     (package-name (symbol-package ':*package*))
     ; => "KEYWORD"  (sbcl, ccl, ecl, abcl, clasp, lispworks)
     ; => "COMMON-LISP"  (acl)

     (package-name (symbol-package '||:*package*))
     ; => "KEYWORD"  (ecl, clasp, lispworks)
     ; => "COMMON-LISP"  (sbcl, ccl, acl)
     ; abcl errors
   #+END_SRC
** Current behavior
   sbcl, ccl:
   ~:xxxx~ is read as a keyword;
   ~||:xxxx~ is read as a symbol in the package named or nicknamed ~""~.

   ecl, clasp, lispworks:
   ~||:xxxx~ and ~:xxxx~ are read as a keyword.

   acl:
   ~:xxxx~ and ~||:xxxx~ are read as a symbol in the package named or nicknamed ~""~.
   ~""~ is by default a global nickname for the ~#:KEYWORD~ package.

   abcl:
   ~:xxxx~ is read as a keyword;
   ~||:xxxx~ syntax cannot be read (attemts result in an error).
** Proposal ALLOW-BUT-KEEP-KEYWORDS
   The ~""~ local nickname should be explicitely allowed. ~:xxxx~ should be always
   read as a keyword regardless of package names or nicknames. ~||:xxxx~ should be
   read as a symbol in the package named or nicknamed by ~""~.
** Proposal ALLOW-FUN
   The ~""~ local nickname should be explicitely allowed. Both ~:xxxx~ and ~||:xxxx~
   should be read as a symbol in the package named or nicknamed by ~""~.
** Links
   See [[https://github.com/s-expressionists/wscl/issues/63][WSCL issue 63]].
